### PR TITLE
Ratings & Reviews

### PR DESCRIPTION
**Pull request by nooccarr**
- Added overall rating, recommendation, characteristics to the NewReview component
- created utils function to keep codebase modularized (capitalize, getLabel)
- nestedObject was used in getLabel to avoid creating similar utils function
- created CharacteristicEntry component to keep NewReview component DRY

### CODE REVIEW

**Comment by nooccarr** [comment]
- dependency material-ui added
- newReview class added to styles.css

**Comment by nooccarr** [comment]
- created Review Summary and Review body
- made  counter.js in utils which counts body length and returns a string to present to user

**Comment by nooccarr** [comment]
- Make input field for nickname and email in NewReview
- Created InputEntry component and moved it to InputEntry.jsx
- Now InputEntry handles input fields for Review summary, Review body, Nickname, and Email

**Comment by psychout98** [comment]
Damn thorough commits

**Pull request merged**
