### PR TITLE
Ratings/Reviews update

### PR DESCRIPTION
**Pull request by nooccarr**
- created review list, review list entry, and new review component
- created utils folder for storing utility functions

Feedback appreciated.

### CODE REVIEW

**Comment by nooccarr** [comment]
- created ratingAndReviews folder
- moved reviews related components to ratingAndReviews folder
- renamed reviews.jsx to RatingAndReviews.jsx
- created ProductBreakdown and RatingBreakdown component

**Comment by nooccarr** [comment]
- Added axios as a dependency in package.json for making HTTP requests to the API
- RatingAndReviews component can make GET request to '/reviews'

**Comment by nooccarr** [comment]
- Used select & options elements to implement sort options for reviews list
- handleSortByChange updates sort property of the state and re-renders the reviews list

**Review by psychout98 — APPROVED** [review]
Looks dandy

**Pull request merged**
